import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/examples/jsm/loaders/DRACOLoader.js';
import {MeshoptDecoder} from 'three/examples/jsm/libs/meshopt_decoder.module.js';
export const GROUPS=[['muscle','肌肉','#dba38e'],['bone','骨骼','#e6e2d7'],['nerve','神經','#decb74'],['artery','動脈','#cb637a'],['vein','靜脈','#7aaed4'],['heart','心臟','#ba5767'],['respiratory','呼吸','#bd98c9'],['digestive','消化','#c99c66'],['urinary','泌尿','#bca3d5'],['endocrine','內分泌','#e5b34b'],['reproductive','生殖','#be8ca4'],['lymphatic','淋巴','#83be84']];
const clean=n=>n.replace(/\.[lr]\.\d+$/,'').replace(/\.\d+$/,'').replace(/\.[lr]$/,'');
const dictionary={'Humerus':'肱骨','Radius':'橈骨','Ulna':'尺骨','Scapula':'肩胛骨','Clavicle':'鎖骨','Biceps brachii':'肱二頭肌','Triceps brachii':'肱三頭肌','Deltoid':'三角肌','Brachialis':'肱肌','Brachioradialis':'肱橈肌','Median nerve':'正中神經','Ulnar nerve':'尺神經','Radial nerve':'橈神經','Axillary nerve':'腋神經','Brachial artery':'肱動脈','Radial artery':'橈動脈','Ulnar artery':'尺動脈','Axillary artery':'腋動脈','Cephalic vein':'頭靜脈','Basilic vein':'貴要靜脈','Median cubital vein':'肘正中靜脈','Femur':'股骨','Tibia':'脛骨','Fibula':'腓骨','Patella':'髕骨','Sternum':'胸骨','Stomach':'胃','Oesophagus':'食道','Liver':'肝臟','Gallbladder':'膽囊','Pancreas':'胰臟','Duodenum':'十二指腸','Jejunum':'空腸','Ascending colon':'升結腸','Transverse colon':'橫結腸','Descending colon':'降結腸','Sigmoid colon':'乙狀結腸','Trachea':'氣管','Kidney':'腎臟','Ureter':'輸尿管','Urinary bladder':'膀胱','Urethra':'尿道','Thyroid gland':'甲狀腺','Suprarenal gland':'腎上腺','Testis':'睪丸','Prostate':'攝護腺','Epididymis':'副睪','Tongue':'舌','Pleura':'胸膜','Left atrium':'左心房','Right atrium':'右心房','Left ventricle':'左心室','Right ventricle':'右心室','Ascending aorta':'升主動脈','Arch of aorta':'主動脈弓','Pulmonary trunk':'肺動脈幹','Superior vena cava':'上腔靜脈','Inferior vena cava':'下腔靜脈','Superior lobe of right lung':'右肺上葉','Middle lobe of right lung':'右肺中葉','Inferior lobe of right lung':'右肺下葉','Superior lobe of left lung':'左肺上葉','Inferior lobe of left lung':'左肺下葉'};
export function label(name){const n=clean(name);return dictionary[n]||n;}
function classify(name,file){if(file==='lymphatic')return'lymphatic';if(file==='skeleton')return'bone';if(file==='muscular')return'muscle';if(file==='nervous')return'nerve';if(file==='cardiovascular'){if(/arter|aorta|arterios|arterial/i.test(name))return'artery';if(/vein|vena|venous/i.test(name))return'vein';return'heart';}if(/lung|bronch|trache|laryn|nasal|nose|pleura|epiglott/i.test(name))return'respiratory';if(/kidney|ureter|urethr|urinary|renal pelvis/i.test(name))return'urinary';if(/hypophys|thyroid|suprarenal|pineal/i.test(name))return'endocrine';if(/testis|epididym|deferens|seminal|prostate|ejaculat|penis/i.test(name))return'reproductive';return'digestive';}
const color=id=>GROUPS.find(g=>g[0]===id)?.[2]||'#cfa393';
export function createEngine(host,notify){
let dead=false,token=0,items=[],selected=null,mode='arm',focus='all',spread=true,parts=false,hidden=new Set(),frame;
const manager=new THREE.LoadingManager();manager.setURLModifier(url=>{const key=url.split('/').pop();return window.ANATOMY_ASSETS?.[key]||url});
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#0a1119');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;host.appendChild(renderer.domElement);
const scene=new THREE.Scene(),root=new THREE.Group();scene.add(root);const camera=new THREE.PerspectiveCamera(35,1,.01,100);camera.position.set(0,0,5);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=.1;controls.maxDistance=40;controls.autoRotateSpeed=.65;
scene.add(new THREE.HemisphereLight(0xd8e9ff,0x565460,2.5));for(const [x,y,z,intensity] of [[-3,4,5,3],[4,1,2,1.8],[0,2,-4,2]]){const light=new THREE.DirectionalLight(0xffffff,intensity);light.position.set(x,y,z);scene.add(light)}
const draco=new DRACOLoader(manager).setDecoderPath('draco/').setDecoderConfig({type:'js'}).setWorkerLimit(2);const loader=new GLTFLoader(manager).setDRACOLoader(draco).setMeshoptDecoder(MeshoptDecoder);
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let down=[0,0];
function emit(){notify({ready:items.length>0,mode,focus,spread,parts,groups:GROUPS.filter(g=>items.some(i=>i.group===g[0])).map(g=>({id:g[0],name:g[1],color:g[2],count:items.filter(i=>i.group===g[0]).length,hidden:hidden.has(g[0])})),count:items.filter(i=>i.object.visible).length,selected:selected?{name:selected.name,zh:label(selected.name),group:selected.group,id:selected.id}:null});}
function clearSelection(){if(selected)selected.object.traverse(m=>{if(m.isMesh){m.material.emissive.set(0);m.material.emissiveIntensity=0}});selected=null;}
function choose(item){clearSelection();selected=item;if(item)item.object.traverse(m=>{if(m.isMesh){m.material.emissive.set('#37b7a6');m.material.emissiveIntensity=.32}});emit();}
function cameraFit(box,instant=true){if(box.isEmpty())return;const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());const dist=Math.max(size.y,size.x/camera.aspect)/2/Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*1.2;camera.position.copy(center).add(new THREE.Vector3(0,0,Math.max(dist,.2)));controls.target.copy(center);camera.near=.001;camera.far=100;camera.updateProjectionMatrix();controls.update();}
function layout(resetCamera=true){const groups=GROUPS.filter(g=>items.some(i=>i.group===g[0])&&!hidden.has(g[0])).map(g=>g[0]);const visible=items.filter(i=>(focus==='all'||i.group===focus)&&!hidden.has(i.group));const cols=Math.max(1,Math.ceil(Math.sqrt(visible.length*1.6)));const sizes=visible.map(i=>i.box.getSize(new THREE.Vector3()));const cellX=Math.max(.13,...sizes.map(s=>s.x))+.1,cellY=Math.max(.13,...sizes.map(s=>s.y))+.12;
const grid=new Map();if(parts){const ordered=[...visible].sort((a,b)=>b.box.getSize(new THREE.Vector3()).y-a.box.getSize(new THREE.Vector3()).y);const rows=[];for(let k=0;k<ordered.length;k+=cols)rows.push(ordered.slice(k,k+cols));const heights=rows.map(row=>Math.max(...row.map(i=>i.box.getSize(new THREE.Vector3()).y))+.1);let y=heights.reduce((a,b)=>a+b,0)/2;rows.forEach((row,r)=>{const widths=row.map(i=>i.box.getSize(new THREE.Vector3()).x+.1);let x=-widths.reduce((a,b)=>a+b,0)/2;row.forEach((i,k)=>{grid.set(i,new THREE.Vector3(x+widths[k]/2,y-heights[r]/2,0).sub(i.center));x+=widths[k];});y-=heights[r];});}const bounds=new THREE.Box3();items.forEach(i=>{i.object.visible=visible.includes(i);if(!i.object.visible)return;const target=new THREE.Vector3();if(parts){target.copy(grid.get(i));}else if(spread&&focus==='all'){const k=groups.indexOf(i.group);const spacing=mode==='arm'?.66:1.15;target.x=(k-(groups.length-1)/2)*spacing;}i.target.copy(target);bounds.union(i.box.clone().translate(target));});if(resetCamera)cameraFit(bounds);emit();}
async function arrayBuffer(file){const asset=window.ANATOMY_ASSETS?.[file];const response=await fetch(asset||'models/'+file);if(!response.ok)throw Error(file+' 下載失敗');return response.arrayBuffer();}
async function load(nextMode){const my=++token;mode=nextMode;focus='all';parts=false;spread=nextMode==='arm';hidden=new Set();clearSelection();notify({loading:true,message:'載入真實解剖模型…'});
const loaded=[];try{let meta=[];if(mode==='arm'){const r=await fetch(window.ANATOMY_ASSETS?.['arm-structures.json']||'models/arm-structures.json');meta=await r.json();}const files=mode==='arm'?['arm-core','arm-upper-limb-right']:['skeleton','muscular','cardiovascular','nervous','visceral','lymphatic'];let done=0;
for(const file of files){const data=await arrayBuffer(file+'.glb');const gltf=await loader.parseAsync(data,'');loaded.push(gltf);notify({loading:true,message:`載入模型 ${++done} / ${files.length}`});if(my!==token||dead)return;}
root.clear();for(const i of items)i.object.traverse(m=>{if(m.isMesh){m.geometry.dispose();m.material.dispose()}});items=[];const map=new Map();
loaded.forEach((gltf,fileIndex)=>{gltf.scene.updateMatrixWorld(true);gltf.scene.traverse(mesh=>{if(!mesh.isMesh)return;let name,group,key;if(mode==='arm'){let parent=mesh;while(parent&&parent.userData.structure===undefined)parent=parent.parent;const record=meta[parent?.userData.structure];if(!record)return;name=record.name;group=record.tissue;key='arm-'+record.id;}else{const assoc=gltf.parser.associations.get(mesh);name=gltf.parser.json.nodes?.[assoc?.nodes]?.name||gltf.parser.json.meshes?.[assoc?.meshes]?.name||mesh.name;if(/\.[gj]\.\d+$/.test(name))return;group=classify(name,files[fileIndex]);key=files[fileIndex]+'-'+name;}
let item=map.get(key);if(!item){item={id:key,name,group,object:new THREE.Group(),target:new THREE.Vector3(),box:new THREE.Box3(),center:new THREE.Vector3()};map.set(key,item);items.push(item);root.add(item.object)}
const geometry=mesh.geometry.clone();for(const key of ['position','normal']){const a=geometry.getAttribute(key);if(a && !(a.array instanceof Float32Array)){const out=new Float32Array(a.count*a.itemSize);for(let k=0;k<a.count;k++){out[k*a.itemSize]=a.getX(k);out[k*a.itemSize+1]=a.getY(k);out[k*a.itemSize+2]=a.getZ(k);}geometry.setAttribute(key,new THREE.BufferAttribute(out,a.itemSize));}}geometry.applyMatrix4(mesh.matrixWorld);const original=Array.isArray(mesh.material)?mesh.material[0]:mesh.material;const material=new THREE.MeshStandardMaterial({color:original?.color||color(group),map:original?.map||null,roughness:.68,metalness:0,side:THREE.DoubleSide});if(mode==='body'||['nerve','artery','vein'].includes(group))material.color.set(color(group));const m=new THREE.Mesh(geometry,material);m.userData.item=item;item.object.add(m);});});
const box=new THREE.Box3().setFromObject(root),center=box.getCenter(new THREE.Vector3()),scale=2.6/box.getSize(new THREE.Vector3()).y;
for(const item of items){item.object.traverse(m=>{if(m.isMesh){m.geometry.translate(-center.x,-center.y,-center.z);m.geometry.scale(scale,scale,scale);}});item.box.setFromObject(item.object);item.box.getCenter(item.center);}
notify({loading:false,message:''});layout();}catch(e){if(my===token)notify({loading:false,error:'模型載入失敗：'+e.message});}finally{for(const gltf of loaded)gltf.scene.traverse(m=>{if(m.isMesh){m.geometry.dispose();}});}}
renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY]});renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects(items.filter(i=>i.object.visible).map(i=>i.object),true);choose(hits[0]?.object.userData.item||null);});
const resize=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();if(items.length)layout();});resize.observe(host);
let last=performance.now();function animate(now){if(dead)return;const dt=Math.min((now-last)/1000,.1);last=now;for(const i of items)i.object.position.lerp(i.target,1-Math.exp(-dt*7));controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(animate)}frame=requestAnimationFrame(animate);
return {load,setFocus(id){focus=id;parts=false;clearSelection();layout()},setSpread(v){spread=v;parts=false;layout()},setParts(v){parts=v;layout()},toggle(id){hidden.has(id)?hidden.delete(id):hidden.add(id);clearSelection();layout()},reset(){layout()},orbit(v){controls.autoRotate=v},zoom(factor){camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target);controls.update()},view(back){layout();if(back)camera.position.z=-Math.abs(camera.position.z);controls.update()},select(id){choose(items.find(i=>i.id===id));},focusSelected(){if(!selected)return;cameraFit(new THREE.Box3().setFromObject(selected.object))},list(){return items.filter(i=>i.object.visible).map(i=>({id:i.id,name:i.name,zh:label(i.name)}))},destroy(){dead=true;++token;cancelAnimationFrame(frame);resize.disconnect();controls.dispose();draco.dispose();for(const i of items)i.object.traverse(m=>{if(m.isMesh){m.geometry.dispose();m.material.map?.dispose();m.material.dispose()}});renderer.dispose();renderer.domElement.remove();},getDiagnostics(){return{mode,focus,spread,parts,count:items.length,visible:items.filter(i=>i.object.visible).length,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,camera:camera.position.toArray(),target:controls.target.toArray(),box:items[0]?.box,positions:items.slice(0,4).map(i=>i.object.position.toArray())}}};
}
