'use client';
import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '../components/ui/tabs';
import {systems} from './anatomy-knowledge';
const groupTopic:Record<string,number>={heart:0,artery:0,vein:0,respiratory:1,nerve:2,bone:3,muscle:4,digestive:5,urinary:6,endocrine:7,lymphatic:8,reproductive:10};
const targets=['heart','respiratory','nerve','bone','muscle','digestive','urinary','endocrine','lymphatic',null,'reproductive'];
export default function Knowledge({focus,selected,busy,onExplore}:{focus:string;selected:any;busy:boolean;onExplore:(group:string)=>void}){
const [topic,setTopic]=useState(4),[organ,setOrgan]=useState<number|null>(0),[answer,setAnswer]=useState(false),[tab,setTab]=useState('structure');
useEffect(()=>{const t=groupTopic[selected?.group||focus];if(t!==undefined)setTopic(t)},[focus,selected?.group]);
useEffect(()=>{setOrgan(0);setAnswer(false)},[topic]);
const s=systems[topic];
return <section className="knowledge" aria-label="人體解剖知識"><div className="knowledge-title"><span>人體解剖教室</span><small>11 系統知識庫</small></div><details className="topic-picker"><summary>切換知識主題：{s.n}</summary><div className="topic-grid">{systems.map((v,i)=><button key={v.en} aria-pressed={topic===i} onClick={()=>{setTopic(i);setAnswer(false);setOrgan(0)}}>{v.n}</button>)}</div></details><div className="knowledge-heading"><h2>{s.n}</h2><span>{s.en}</span></div><p className="knowledge-intro">{s.intro}</p>{targets[topic]?<button className="explore-topic" disabled={busy} onClick={()=>onExplore(targets[topic]!)}>{topic===0?'3D 查看心臟':`3D 查看${s.n}`}</button>:<p className="coverage-note">皮膚系統目前提供文字教學，尚未包含 3D 模型。</p>}{topic===0&&<p className="coverage-note">動脈與靜脈可由畫面下方分別選取。</p>}{topic===8&&<p className="coverage-note">3D 圖層呈現脾臟與胸腺；以下文字涵蓋更多淋巴構造。</p>}{topic===10&&<p className="coverage-note">3D 為男性構造；女性構造的功能亦收錄於下方說明。</p>}
<Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="knowledge-tabs"><TabsTrigger value="structure">構造與功能</TabsTrigger><TabsTrigger value="teaching">教學與問答</TabsTrigger></TabsList><TabsContent value="structure"><div className="knowledge-organs">{s.org.map((o,i)=><div key={o[0]} className={organ===i?'open':''}><button aria-expanded={organ===i} onClick={()=>setOrgan(organ===i?null:i)}><span>{String(i+1).padStart(2,'0')}</span>{o[0]}<b>{organ===i?'−':'＋'}</b></button>{organ===i&&<p>{o[1]}</p>}</div>)}</div></TabsContent><TabsContent value="teaching"><article className="teaching-note"><h3>帶學員這樣看</h3><p>{s.note}</p></article><article className="teaching-question"><small>課堂提問</small><h3>{s.q}</h3><button aria-expanded={answer} onClick={()=>setAnswer(!answer)}>{answer?'收起解答':'顯示解答'}</button>{answer&&<p className="teaching-answer">{s.a}</p>}</article></TabsContent></Tabs>
<details className="reading-note"><summary>解剖位置與讀圖提醒</summary><p>正面觀察時，人體右側在觀看者左邊。展開／拆解會移動模型；講解正常位置與器官相互關係前，請先組合模型。</p><p>文字涵蓋系統整體知識，並非每項構造都有對應的 3D 網格。模型上的點選名稱與本面板的系統說明分開呈現。</p></details><p className="knowledge-source">教材整理參考 <a href="https://openstax.org/books/anatomy-and-physiology-2e/pages/1-2-structural-organization-of-the-human-body" target="_blank" rel="noreferrer">OpenStax Anatomy and Physiology 2e</a>。<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noreferrer">CC BY-NC-SA 4.0</a>。</p></section>
}
