'use client';
import {useEffect,useRef,useState} from 'react';
import {Tabs,TabsList,TabsTrigger} from '../components/ui/tabs';
import {createEngine,GROUPS} from './anatomy-engine';
import Knowledge from './Knowledge';
export default function Studio(){const host=useRef<HTMLDivElement>(null),engine=useRef<any>(null);const [state,setState]=useState<any>({loading:true,groups:[],focus:'all',spread:true,mode:'arm'}),[orbit,setOrbit]=useState(false),[panel,setPanel]=useState(true),[query,setQuery]=useState('');
useEffect(()=>{let e:any;try{e=createEngine(host.current,(v:any)=>setState((s:any)=>({...s,...v})));engine.current=e;(window as any).anatomyDiagnostics=()=>e.getDiagnostics();e.load('arm');}catch(err:any){setState((s:any)=>({...s,loading:false,error:'無法啟動 3D 顯示。請使用支援 WebGL 2 的瀏覽器，並開啟硬體加速。'}));}return()=>e?.destroy()},[]);
const explore=async(group:string)=>{setQuery('');if(state.mode==='arm'&&!['muscle','bone','nerve','artery','vein'].includes(group))await engine.current.load('body');engine.current.setFocus(group);};
const locked=state.loading||!!state.error;const groups=state.groups||[];const selected=state.selected;const list=engine.current?.list().filter((i:any)=>!query||(i.zh+' '+i.name).toLowerCase().includes(query.toLowerCase()))||[];
return <div className="studio"><header className="studiohead"><div><p className="kicker">ANATOMY, IN MOTION</p><h1>人體解剖，展開來看。</h1><p>旋轉、拆解、再組合。從立體位置理解身體。</p></div><div className="topactions"><button className="primary" disabled={locked} onClick={()=>engine.current.setSpread(!state.spread)}>{state.spread?'組合模型':'展開各系統'}</button><button aria-pressed={orbit} onClick={()=>{setOrbit(!orbit);engine.current?.orbit(!orbit)}}>自動旋轉</button><button onClick={()=>engine.current?.reset()}>重設視角</button><button aria-expanded={panel} onClick={()=>setPanel(!panel)}>{panel?'收起說明':'顯示說明'}</button></div></header><div className="stage" ref={host} aria-label="可旋轉、選取與拆解的三維人體模型"/><div className="modebar"><Tabs value={state.mode} onValueChange={v=>{if(!locked){setQuery('');engine.current.load(v);}}}><TabsList><TabsTrigger value="arm" disabled={locked}>右上肢・影片效果</TabsTrigger><TabsTrigger value="body" disabled={locked}>全身・系統探索</TabsTrigger></TabsList></Tabs><span>{state.mode==='arm'?'RIGHT UPPER LIMB':'WHOLE BODY'}</span></div><div className="viewtools"><button onClick={()=>engine.current?.view(false)}>正面</button><button onClick={()=>engine.current?.view(true)}>背面</button><button aria-label="放大" onClick={()=>engine.current?.zoom(.8)}>＋</button><button aria-label="縮小" onClick={()=>engine.current?.zoom(1.25)}>−</button></div>{state.loading&&<div className="loadcard" role="status"><span className="spinner"/><b>{state.message||'準備 3D 解剖教室…'}</b><p>首次載入需片刻，完成後即可自由旋轉。</p></div>}{state.error&&<div className="loadcard" role="alert"><b>{state.error}</b><button onClick={()=>location.reload()}>重新載入</button></div>}
{panel&&<aside className="infopanel">{state.focus!=='all'&&<div className="panelbuttons"><button disabled={locked} className="primary" onClick={()=>engine.current.setParts(!state.parts)}>{state.parts?'組合此系統':'拆開個別構造'}</button><button onClick={()=>{engine.current.setFocus('all');setQuery('')}}>返回總覽</button></div>}{selected?<article className="picked"><small>已選取構造</small><h2>{selected.zh}</h2>{selected.zh!==selected.name&&<p>{selected.name}</p>}<span>{GROUPS.find((g:any)=>g[0]===selected.group)?.[1]}</span><button onClick={()=>engine.current.focusSelected()}>放大此構造</button></article>:<div className="pickhint">點選模型上的一個構造<br/><small>細小構造也可從清單選取</small></div>}<Knowledge focus={state.focus} selected={selected} busy={locked} onExplore={explore}/><details className="controls-details"><summary>3D 操作與構造選取</summary><div className="paneltitle"><span>教學操作</span><span className="muted">3D ATLAS</span></div><p className="instruction">拖曳旋轉 · 滾輪縮放<br/>點選模型查看構造名稱</p><div className="panelrule"/><p className="minititle">{state.focus==='all'?'系統總覽':GROUPS.find((g:any)=>g[0]===state.focus)?.[1]+'・單獨觀察'}</p><p className="instruction">{state.focus==='all'?'點下方系統名稱，單獨查看；「展開各系統」可比較空間層次。':'可拆成個別構造，觀察每一塊肌肉、骨骼或器官。'}</p>
<details className="structurelist"><summary>構造清單（{state.count||0}）</summary><input aria-label="搜尋構造" placeholder="中文或英文構造名稱" value={query} onChange={e=>setQuery(e.target.value)}/><div>{list.slice(0,150).map((i:any)=><button key={i.id} onClick={()=>engine.current.select(i.id)}>{i.zh}</button>)}{list.length>150&&<p>尚有 {list.length-150} 筆，請輸入名稱縮小範圍。</p>}{!list.length&&<p>沒有符合的構造。</p>}</div></details></details><details className="about"><summary>教學範圍與模型來源</summary><p>3D 版使用真實解剖網格。展開與拆解會移動模型，位置關係請以組合模式觀察。細部名稱保留模型英文，常用構造附繁體中文。</p><p>全身為男性模型；淋巴系統呈現脾臟與胸腺；皮膚與女性生殖構造未包含在這組 3D 資料中，可在本面板切換至對應的知識主題閱讀。</p><p>模型：Z-Anatomy / BodyParts3D；右上肢另含 Open 3D Model。<a href="https://github.com/Z-Anatomy/Models-of-human-anatomy" target="_blank" rel="noreferrer">來源與授權</a>。教學模型可能有誤差，不能作為臨床定位依據。</p></details></aside>}
<div className="systembar" aria-label="解剖系統選擇"><button className={state.focus==='all'?'all active':'all'} disabled={locked} onClick={()=>{engine.current.setFocus('all');setQuery('')}}>全部系統</button>{groups.map((g:any)=><div className="systemchip" key={g.id}><button className={state.focus===g.id?'active':''} style={{'--tissue':g.color} as any} disabled={locked} onClick={()=>{engine.current.setFocus(g.id);setQuery('')}}><span style={{background:g.color}}/>{g.name}<small>{g.count}</small></button><button className="eye" disabled={locked} aria-label={(g.hidden?'顯示':'隱藏')+g.name} aria-pressed={!g.hidden} onClick={()=>engine.current.toggle(g.id)}>{g.hidden?'○':'●'}</button></div>)}</div><div className="studiofoot"><span>{state.parts?'構造分解模式':state.focus!=='all'?'單系統觀察':state.spread?'系統展開模式':'解剖位置・組合模式'} · {state.count||0} 個構造</span><span>真實 3D 模型 · 拖曳旋轉 / 觸控雙指縮放</span></div></div>}
